### ISSUE TITLE
[dev] drag/drop widgets freezing

### ISSUE THREAD

**Issue by hpsaturn** [jgauchia/IceNav-v3#100]
## Overview

When you try to move to the second window, and touch the compass, the widget is selected and it is freezing the device. But, the custom widget editor works fine.Maybe is only with a fast drag (trying to pass to the second window

**Comment by jgauchia** [comment]
Has the widget issue also been resolved with the latest commit?

**Comment by hpsaturn** [comment]
nop, the issue still there. Only try to play with the widget, and perform a fast swipe to the right (like a window or section change, and you have the issue).

**Comment by jgauchia** [comment]
Ok, I'll try, thank you

**Comment by jgauchia** [comment]
Added Button to enable drag&drop widgets (edit mode) when it's active.
